### ISSUE TITLE
testPeerRemovalNontrivial fails

### ISSUE THREAD

**Issue by Pitel** [ls1intum/jReto#6]
Current git, `mvn package` fails:
```
-------------------------------------------------------------------------------
Test set: jReto.integration.DiscoveryTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.883 sec <<< FAILURE!
testPeerRemovalNontrivial(jReto.integration.DiscoveryTest)  Time elapsed: 0.14 sec  <<< ERROR!
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at de.tum.in.www1.jReto.routing.Router.disconnectAll(Router.java:599)
	at de.tum.in.www1.jReto.routing.DefaultRouter.stop(DefaultRouter.java:76)
	at de.tum.in.www1.jReto.LocalPeer.stop(LocalPeer.java:215)
	at jReto.integration.DiscoveryTest.lambda$testPeerRemoval$6(DiscoveryTest.java:117)
	at de.tum.in.www1.jReto.util.CountDown.countDown(CountDown.java:17)
	at jReto.integration.DiscoveryTest.lambda$testPeerRemoval$10(DiscoveryTest.java:132)
	at de.tum.in.www1.jReto.LocalPeer.addNode(LocalPeer.java:269)
	at de.tum.in.www1.jReto.LocalPeer.access$400(LocalPeer.java:32)
	at de.tum.in.www1.jReto.LocalPeer$2.onNodeFound(LocalPeer.java:134)
	at de.tum.in.www1.jReto.routing.Router.lambda$updateNodes$1(Router.java:569)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at de.tum.in.www1.jReto.routing.Router.updateNodes(Router.java:569)
	at de.tum.in.www1.jReto.routing.Router.handleLinkStatePacket(Router.java:577)
	at de.tum.in.www1.jReto.routing.Router$1.handlePacket(Router.java:127)
	at de.tum.in.www1.jReto.routing.FloodingPacketManager.handlePacket(FloodingPacketManager.java:75)
	at de.tum.in.www1.jReto.routing.Node.handlePacket(Node.java:184)
	at de.tum.in.www1.jReto.connectivity.PacketConnection$1.onDataReceived(PacketConnection.java:93)
	at jReto.module.dummy.DummyConnection$1.run(DummyConnection.java:42)
	at jReto.util.RunLoop.start(RunLoop.java:29)
	at jReto.integration.DiscoveryTest.testPeerRemoval(DiscoveryTest.java:141)
	at jReto.integration.DiscoveryTest.testPeerRemovalNontrivial(DiscoveryTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by krusche** [comment]
Could you provide a fix in a pull request?

**Comment by Pitel** [comment]
No, sorry, I can't. I was just considering using it in my project, but I couldn't even build it. But if someone else provides the fix, I can test it.
